### PR TITLE
Resolved #3: Background buffer flow fix

### LINKED ISSUE #3: Quiet mode randomly crash
When I use this plugin for my project, the server unexpectedly falls. I can stand this just happen in one-time, but I can't if it occurs million times :-1:

### PR DESCRIPTION
**Pull request by hiroaki-yamamoto**

### CODE REVIEW

File: tests/unit/specs/spec_server.coffee [hunk 1]
```diff
@@ -33,6 +33,7 @@ describe "Server unit tests (test mode)", ->
     exec_ret =
       "stdout":
         "pipe": sinon.spy()
+        "on": sinon.spy()
```
Comment (hiroaki-yamamoto) [inline tests/unit/specs/spec_server.coffee]: Not needed
